#!/usr/bin/env bash
#
# import-models.sh
#
# Imports the BaseModels/ and GeneratedModels/ folders from the archived
# https://github.com/microsoftgraph/msgraph-sdk-objc-models repository into
# this package and regenerates the public aggregate header
# MSGraphClientSDK/MSGraphClientSDK/include/MSGraphClientModels.h that
# re-exports every model header.
#
# Run this once (or whenever you want to refresh the models), then commit
# the resulting changes:
#
#     ./Scripts/import-models.sh
#     git add MSGraphClientSDK/MSGraphClientSDK/BaseModels \
#             MSGraphClientSDK/MSGraphClientSDK/GeneratedModels \
#             MSGraphClientSDK/MSGraphClientSDK/include/MSGraphClientModels.h
#     git commit -m "Import BaseModels and GeneratedModels"
#
# Optionally pin a specific upstream ref by exporting MODELS_REF, e.g.:
#     MODELS_REF=1.3.0 ./Scripts/import-models.sh
#
set -euo pipefail

MODELS_REPO="${MODELS_REPO:-https://github.com/microsoftgraph/msgraph-sdk-objc-models.git}"
MODELS_REF="${MODELS_REF:-master}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SDK_ROOT="${REPO_ROOT}/MSGraphClientSDK/MSGraphClientSDK"
INCLUDE_DIR="${SDK_ROOT}/include"
DEST_BASE="${SDK_ROOT}/BaseModels"
DEST_GEN="${SDK_ROOT}/GeneratedModels"
AGGREGATE_HEADER="${INCLUDE_DIR}/MSGraphClientModels.h"

WORK_DIR="$(mktemp -d -t msgraph-models-XXXXXX)"
trap 'rm -rf "${WORK_DIR}"' EXIT

echo "==> Cloning ${MODELS_REPO} (${MODELS_REF}) into ${WORK_DIR}"
git clone --depth 1 --branch "${MODELS_REF}" "${MODELS_REPO}" "${WORK_DIR}/models" \
    2>/dev/null \
    || git clone "${MODELS_REPO}" "${WORK_DIR}/models"

if [[ ! -d "${WORK_DIR}/models/BaseModels" || ! -d "${WORK_DIR}/models/GeneratedModels" ]]; then
    echo "ERROR: BaseModels/ or GeneratedModels/ not found in upstream repo" >&2
    exit 1
fi

echo "==> Replacing ${DEST_BASE}"
rm -rf "${DEST_BASE}"
mkdir -p "${DEST_BASE}"
cp "${WORK_DIR}/models/BaseModels/"*.{h,m} "${DEST_BASE}/"

echo "==> Replacing ${DEST_GEN}"
rm -rf "${DEST_GEN}"
mkdir -p "${DEST_GEN}"
cp "${WORK_DIR}/models/GeneratedModels/"*.{h,m} "${DEST_GEN}/"

echo "==> Generating aggregate header ${AGGREGATE_HEADER}"
mkdir -p "${INCLUDE_DIR}"
{
    cat <<'HEADER'
//
// MSGraphClientModels.h
//
// AUTO-GENERATED by Scripts/import-models.sh. DO NOT EDIT BY HAND.
// Re-exports every public model header from BaseModels/ and GeneratedModels/
// so that Swift Package Manager's umbrella header makes them part of the
// MSGraphClientSDK module's public API.
//

#ifndef MSGraphClientModels_h
#define MSGraphClientModels_h

HEADER

    echo "// BaseModels"
    (cd "${DEST_BASE}" && ls -1 *.h | sort) | while read -r h; do
        echo "#import \"../BaseModels/${h}\""
    done

    echo ""
    echo "// GeneratedModels"
    (cd "${DEST_GEN}" && ls -1 *.h | sort) | while read -r h; do
        echo "#import \"../GeneratedModels/${h}\""
    done

    cat <<'FOOTER'

#endif /* MSGraphClientModels_h */
FOOTER
} > "${AGGREGATE_HEADER}"

base_count=$(ls -1 "${DEST_BASE}"/*.h 2>/dev/null | wc -l | tr -d ' ')
gen_count=$(ls -1 "${DEST_GEN}"/*.h 2>/dev/null | wc -l | tr -d ' ')
echo "==> Done. Imported ${base_count} BaseModels headers and ${gen_count} GeneratedModels headers."
echo "    Review changes with: git status"
